### ISSUE TITLE
Remove pipe character ( | ) in titleTempalte

### ISSUE THREAD

**Issue by fartinmartin** [spences10/react-seo-component#83]
**Is your feature request related to a problem? Please describe.**
When configuring a `titleTemplate` users are forced to use the formatting as described on [line 164 of SEO.tsx](https://github.com/spences10/react-seo-component/blob/dcfe72771036676cd4df68d02af91811143b3b7e/src/seo.tsx#L164). It would be nice to not be forced to have a pipe character in our site's title when using `titleTemplate`.

**Describe the solution you'd like**
Don't include the pipe character in the `titleTemplate` by default.

**Describe alternatives you've considered**
I have considered the fact that the ability to override this already exists and I am just missing it. 😝

**Comment by spences10** [comment]
Hey @fartinmartin thanks for the suggestion!

Yes, currently the pipe [is hardcoded] I can pic this up of it could be a great first issue or contribution if you're interested?

Otherwise I'll pick it up in due course, I'm not entirely sure how to implement this rn, maybe a optional parameter for the separator which defaults to that if nothing is input?

[is hardcoded]: https://github.com/spences10/react-seo-component/blob/dcfe72771036676cd4df68d02af91811143b3b7e/src/seo.tsx#L164
