### ISSUE TITLE
Not working for facebook social cards

### ISSUE THREAD

**Issue by MartinSchere** [spences10/react-seo-component#89]
When using the [Facebook social debugger](https://developers.facebook.com/tools/debug/), the response code is a 404 and it does not fetch the og:image, og:title, etc. 

**To Reproduce**
1. Deploy the site, copy url
2. Go to the debugger (link above), paste url and click "debug"
3. See error

**Expected behavior**
It should render the card correctly, as it does with twitter

**Screenshots**
![Polo issue](https://user-images.githubusercontent.com/61954243/107798446-e60bdd00-6d3a-11eb-9dc3-c2c9483d2cd3.PNG)

**Additional context**
Here's the link to my dummy site: https://polo-dev.netlify.app/

**Comment by spences10** [comment]
Hey @MartinSchere thanks for taking an interest in the project 👍 

I'll be honest I personally don't use FB so have never tested it for that, have you tried using it without the FB debugger?

I know sometimes with the Twitter Debugger it can give inconsistent results, that's mainly because I use a serverless function to generate the image.

If that's not the case and it flat out doesn't work I'm happy to listen to any suggestions you have and open to PRs 🙏 

Thanks again!

**Comment by MartinSchere** [comment]
My error was very dumb, I forgot to use the plugin for react-helmet so it wasn't generating anything during pre-render

**Comment by spences10** [comment]
Yeah, it is in the docs, I did think about adding it as a peer dep but my opinion was that everyone would be using it already 😂

Ok, so cool to close the issue?
